language: android
dist: trusty
jdk: openjdk11

android:
  components:
    - android-29
    - build-tools-29.0.3

env:
  global:
    # GH_TOKEN
    - secure: "n7blhZYs6/0J+1q/MP0U9aOTuWUxLDwg+O08km4H1dVIMMCx0POTyNW7kLQ1m0oAcBateMFStRpuBAObR5h6SgWDC50SbKYjWaeZrqrA0EKpd5yAsXSbg6y5F8jobogd2kfyHJtgdPU5laysfw0jVOl8Vt3WwXP0JnfNT2fzSSv6B/scDnkFj0XjuOLRMW508L8JYY6d9J3kXXvOIt14M0hGUGbC+h7zFArRgwfXnPjNZ1cWrXXqjOe9fjHkwRGJ3QnwQxsiM6M3JTLtGk3SSyJMyNI7CTGH9M5jpZzcd3TkRkS26Evx8dnUENH5giB9cFpSgnRR5dW/UykxMlamlgEIdMgKepjWRbWR8uks1FP9pl1Q6Bw8dBMUr8baWq41Z65cD8ucyNhcUfsGIaJoPxKVBF0gke8NWNlbOW7Auo1mBxpxRJ2X/U3N0zniij7zz4MFdo1fTHb1jY7G9UFchWDnT9Moi97mv5+vzL+R1R0EIsUE9DrrjPeaC/lNTFp4kVUdUbZT91kce1CP2XQfQ8WGfwI0V8E1mzj8/0VoXyKj7XZIf7x3mZALSPNyYWc8pzIScsrPBB0ZTLKeWY3iKGTzzWz4lZ9e9P8FBsStxCV8tiQkJLd9hgNtvReVFBpSGMXZnzlI3quW38YaX0m8IgendFs9gmeYKiTmZJMUgSs="
    - ORG_GRADLE_PROJECT_sonatypeUsername=samuelg
    # Encrypted ORG_GRADLE_PROJECT_sonatypePassword
    - secure: "mirdhAp1EK1CLhKoK5fdFP5UtExz9Irc35YLAiyA5CiIdMwLI8+d86UtenIcCD1Urdbaghn//mA/EG28ueR4lWW5YaMcP0mG+Hz6dlClqS1kPj8JPqnWgIZwW4Znhko9ZPsCLBWIdfxkXhftsCJu7y0rXUQgTxf1vxQabCNVaBLLDFagk3z/9VLoM6Yo/NTezfBpeKgEjwDHJeD/SYfYwtqB6v5BGNaVrJv5m5oB9a2UQqvkOvvLfVfS8u3FloELG4cjMfBljpyQLY637TzUPhFfUvmmc38cF4X9yakDRZgMzlLaOvj2MN/LqVXjtpcnqqsxRhaQcdQjofNIEZD+GZwy0QJ8g1DcYHBjIEzfO0QZ/2GMzNZrWCWrf0HYHYkVQUEG2/sT2mUjei+K4ydcqavj6Q+byNu6vCDnkM/tetGWCMFjEdvVk1S09Dh7BkO3OTJKmdj6nr/ZTi9VUKjKssAL73fZIAd8W+mVPOYWeilNbb+RAmFoMl+8RM1AjwsjZDnCQQ9rbay5Vt1AUm25dF03fJHOGyVpoMS4+VzBowlETn3fjcDkq6kL6FQaFyjDLjJiU3j8BcEsvQ6+zb376SBPWOwSU+UIEijQISlM4ayLNnQGEDk/i4tAVkmUjCI3mYRhCQJKd9j0Bp48OztXYhFbbkHmVSVuQz/rghxKySo="
    # Encrypted SIGNING_PASSWORD (encrypted SIGNING_KEY, Base64 encoded, is set in Travis environment variables)
    - secure: "EdF+292xtPwQP4cuYfgEkHQn09JFtVLl2w59Ubudvv2Hx9Cud/sXQq1w6CcB6aD3gzblIq/hnZqzXtquHs3a5ydvxat+UmEitdyULOqMDKehVTgx6JmOBHrZ70ASsTxQEnau63W8rAeP/PsqocxIhX4rZOLksr1IfOGZiqmQfK6lVCZTuLMhixeyk96yjdbguXI3NKc377I5M2KMYPvv9zmWZhF6lKXB9pxLXv6/W4eYC1NoZkdsxsTfHsiWrfXEG5K5T5OspzwEByJssVn4lLcqzmZoW/BzspNBeauDqVKF8bpQJ5LnNgGMt7tod4b4N8cdU8N0BMIhRQ4RU39D+O94XKVE1DHO5izafFA9kD0xcmg/1imtnKk5nxy/S0dJD8n5OceLbLtln3a5mIbPALF81L5QLksFfnji2Bj6PBokULKXzQBVg9cKild75hpT2P/L6ueLw4LvmCB5IXdUBeFrFMPjBuMgPs/jbRDcrVbtnlhbMK749Yncfl19i7mjNiMcKNMTP59MfzZR8elnXDV0MY06h2+q7/GXLTNPLU0dCf0eAnn4RaSPme2mmLpxYWkCBLKuTKu+VeqalR9fq914oMTyLOq4Y/BfSu6x4qLXhvECefitzrjWTXlShrp1n1AMfhYHnLIvzoxZZoRVJ7weJOB8L/1R0FNEPlhu8+o="

script: ./gradlew build testRelease connectedCheck --exclude-task testDebugUnitTest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1
      ./gradlew dokkaHtml
      mkdir docs
      cp -r webflows/build/dokka/html/. docs/.
    fi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    verbose: true
    local_dir: docs
    on:
      repo: schibsted/account-sdk-android-web
      branch: master

  - provider: script
    skip_cleanup: true
    script: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
    on:
      repo: schibsted/account-sdk-android-web
      tags: true
