group: vm
jdk: openjdk11
language: android

android:
  components:
    - android-29
    - build-tools-29.0.3

script: ./gradlew build testRelease connectedCheck --exclude-task testDebugUnitTest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
